spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.100:1521:XE
    username: "c##bootproject"
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
    thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true 
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug  
    org.hibernate.type: trace
    
cos:
  key: cos6553